version: "3.3"
services:
  db:
    image: postgres:9.6
    container_name: pg_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb