version: "3.3"
services:
  #  Adapted from https://hub.docker.com/_/postgres
  db:
    image: postgres
    container_name: pg_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student