---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: studentdb
          POSTGRES_PASSWORD: student
          POSTGRES_USER: student
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      USING_COVERAGE: '3.6,3.8'

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: "actions/checkout@v2"
#       Adapter from https://github.com/actions/setup-python
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name : Cache multiple paths
        uses : actions/cache@v2
        with :
          path : |
            venv
          key : ${{ runner.os }}
      - name: "Install dependencies and run tests"
        run: |
          make test
      - name: Send email if failed
        uses: dawidd6/action-send-mail@v2.4.0
        if: ${{ failure() }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job failed
          to: ${{secrets.TO_EMAIL}}
          from: ${{secrets.FROM_EMAIL}}
          body: More details https://github.com/happytomatoe/data-modeling-with-postgres/actions
